package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BasicMaster generated by hbm2java
 */
@Entity
@Table(name="basic_master"
    ,catalog="govt_jute_mill_payroll"
)
public class BasicMaster  implements java.io.Serializable {


     private Integer basicId;
     private BasicGrade basicGrade;
     private BasicIncrement basicIncrement;
     private int basicCd;
     private double basicMain;
     private Set<MasterData> masterDatas = new HashSet<MasterData>(0);

    public BasicMaster() {
    }

	
    public BasicMaster(BasicGrade basicGrade, BasicIncrement basicIncrement, int basicCd, double basicMain) {
        this.basicGrade = basicGrade;
        this.basicIncrement = basicIncrement;
        this.basicCd = basicCd;
        this.basicMain = basicMain;
    }
    public BasicMaster(BasicGrade basicGrade, BasicIncrement basicIncrement, int basicCd, double basicMain, Set<MasterData> masterDatas) {
       this.basicGrade = basicGrade;
       this.basicIncrement = basicIncrement;
       this.basicCd = basicCd;
       this.basicMain = basicMain;
       this.masterDatas = masterDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="basic_id", unique=true, nullable=false)
    public Integer getBasicId() {
        return this.basicId;
    }
    
    public void setBasicId(Integer basicId) {
        this.basicId = basicId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grade_id", nullable=false)
    public BasicGrade getBasicGrade() {
        return this.basicGrade;
    }
    
    public void setBasicGrade(BasicGrade basicGrade) {
        this.basicGrade = basicGrade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="increment_id", nullable=false)
    public BasicIncrement getBasicIncrement() {
        return this.basicIncrement;
    }
    
    public void setBasicIncrement(BasicIncrement basicIncrement) {
        this.basicIncrement = basicIncrement;
    }

    
    @Column(name="basic_cd", nullable=false)
    public int getBasicCd() {
        return this.basicCd;
    }
    
    public void setBasicCd(int basicCd) {
        this.basicCd = basicCd;
    }

    
    @Column(name="basic_main", nullable=false, precision=22, scale=0)
    public double getBasicMain() {
        return this.basicMain;
    }
    
    public void setBasicMain(double basicMain) {
        this.basicMain = basicMain;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="basicMaster")
    public Set<MasterData> getMasterDatas() {
        return this.masterDatas;
    }
    
    public void setMasterDatas(Set<MasterData> masterDatas) {
        this.masterDatas = masterDatas;
    }




}


