package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BasicGrade generated by hbm2java
 */
@Entity
@Table(name="basic_grade"
    ,catalog="govt_jute_mill_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="grade_cd") 
)
public class BasicGrade  implements java.io.Serializable {


     private Integer gradeId;
     private int gradeCd;
     private double scaleStart;
     private double scaleEnd;
     private int totalStep;
     private Set<BasicMaster> basicMasters = new HashSet<BasicMaster>(0);

    public BasicGrade() {
    }

	
    public BasicGrade(int gradeCd, double scaleStart, double scaleEnd, int totalStep) {
        this.gradeCd = gradeCd;
        this.scaleStart = scaleStart;
        this.scaleEnd = scaleEnd;
        this.totalStep = totalStep;
    }
    public BasicGrade(int gradeCd, double scaleStart, double scaleEnd, int totalStep, Set<BasicMaster> basicMasters) {
       this.gradeCd = gradeCd;
       this.scaleStart = scaleStart;
       this.scaleEnd = scaleEnd;
       this.totalStep = totalStep;
       this.basicMasters = basicMasters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="grade_id", unique=true, nullable=false)
    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    
    @Column(name="grade_cd", unique=true, nullable=false)
    public int getGradeCd() {
        return this.gradeCd;
    }
    
    public void setGradeCd(int gradeCd) {
        this.gradeCd = gradeCd;
    }

    
    @Column(name="scale_start", nullable=false, precision=22, scale=0)
    public double getScaleStart() {
        return this.scaleStart;
    }
    
    public void setScaleStart(double scaleStart) {
        this.scaleStart = scaleStart;
    }

    
    @Column(name="scale_end", nullable=false, precision=22, scale=0)
    public double getScaleEnd() {
        return this.scaleEnd;
    }
    
    public void setScaleEnd(double scaleEnd) {
        this.scaleEnd = scaleEnd;
    }

    
    @Column(name="total_step", nullable=false)
    public int getTotalStep() {
        return this.totalStep;
    }
    
    public void setTotalStep(int totalStep) {
        this.totalStep = totalStep;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="basicGrade")
    public Set<BasicMaster> getBasicMasters() {
        return this.basicMasters;
    }
    
    public void setBasicMasters(Set<BasicMaster> basicMasters) {
        this.basicMasters = basicMasters;
    }




}


