package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BasicIncrement generated by hbm2java
 */
@Entity
@Table(name="basic_increment"
    ,catalog="govt_jute_mill_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="increment_cd") 
)
public class BasicIncrement  implements java.io.Serializable {


     private Integer incrementId;
     private int incrementCd;
     private int incrementName;
     private Set<BasicMaster> basicMasters = new HashSet<BasicMaster>(0);

    public BasicIncrement() {
    }

	
    public BasicIncrement(int incrementCd, int incrementName) {
        this.incrementCd = incrementCd;
        this.incrementName = incrementName;
    }
    public BasicIncrement(int incrementCd, int incrementName, Set<BasicMaster> basicMasters) {
       this.incrementCd = incrementCd;
       this.incrementName = incrementName;
       this.basicMasters = basicMasters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="increment_id", unique=true, nullable=false)
    public Integer getIncrementId() {
        return this.incrementId;
    }
    
    public void setIncrementId(Integer incrementId) {
        this.incrementId = incrementId;
    }

    
    @Column(name="increment_cd", unique=true, nullable=false)
    public int getIncrementCd() {
        return this.incrementCd;
    }
    
    public void setIncrementCd(int incrementCd) {
        this.incrementCd = incrementCd;
    }

    
    @Column(name="increment_name", nullable=false)
    public int getIncrementName() {
        return this.incrementName;
    }
    
    public void setIncrementName(int incrementName) {
        this.incrementName = incrementName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="basicIncrement")
    public Set<BasicMaster> getBasicMasters() {
        return this.basicMasters;
    }
    
    public void setBasicMasters(Set<BasicMaster> basicMasters) {
        this.basicMasters = basicMasters;
    }




}


