package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,catalog="govt_jute_mill_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="department_cd") 
)
public class Department  implements java.io.Serializable {


     private Integer departmentId;
     private int departmentCd;
     private String departmentName;
     private Set<MasterData> masterDatas = new HashSet<MasterData>(0);

    public Department() {
    }

	
    public Department(int departmentCd, String departmentName) {
        this.departmentCd = departmentCd;
        this.departmentName = departmentName;
    }
    public Department(int departmentCd, String departmentName, Set<MasterData> masterDatas) {
       this.departmentCd = departmentCd;
       this.departmentName = departmentName;
       this.masterDatas = masterDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="department_id", unique=true, nullable=false)
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="department_cd", unique=true, nullable=false)
    public int getDepartmentCd() {
        return this.departmentCd;
    }
    
    public void setDepartmentCd(int departmentCd) {
        this.departmentCd = departmentCd;
    }

    
    @Column(name="department_name", nullable=false, length=45)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set<MasterData> getMasterDatas() {
        return this.masterDatas;
    }
    
    public void setMasterDatas(Set<MasterData> masterDatas) {
        this.masterDatas = masterDatas;
    }




}


