package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name="designation"
    ,catalog="govt_jute_mill_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="designation_cd") 
)
public class Designation  implements java.io.Serializable {


     private Integer designationId;
     private int designationCd;
     private String designationName;
     private Set<MasterData> masterDatas = new HashSet<MasterData>(0);

    public Designation() {
    }

	
    public Designation(int designationCd, String designationName) {
        this.designationCd = designationCd;
        this.designationName = designationName;
    }
    public Designation(int designationCd, String designationName, Set<MasterData> masterDatas) {
       this.designationCd = designationCd;
       this.designationName = designationName;
       this.masterDatas = masterDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="designation_id", unique=true, nullable=false)
    public Integer getDesignationId() {
        return this.designationId;
    }
    
    public void setDesignationId(Integer designationId) {
        this.designationId = designationId;
    }

    
    @Column(name="designation_cd", unique=true, nullable=false)
    public int getDesignationCd() {
        return this.designationCd;
    }
    
    public void setDesignationCd(int designationCd) {
        this.designationCd = designationCd;
    }

    
    @Column(name="designation_name", nullable=false, length=45)
    public String getDesignationName() {
        return this.designationName;
    }
    
    public void setDesignationName(String designationName) {
        this.designationName = designationName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="designation")
    public Set<MasterData> getMasterDatas() {
        return this.masterDatas;
    }
    
    public void setMasterDatas(Set<MasterData> masterDatas) {
        this.masterDatas = masterDatas;
    }




}


