package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * House generated by hbm2java
 */
@Entity
@Table(name="house"
    ,catalog="govt_jute_mill_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="house_cd") 
)
public class House  implements java.io.Serializable {


     private Integer houseId;
     private int houseCd;
     private String houseName;
     private double houseRent;
     private Set<MasterDeduction> masterDeductions = new HashSet<MasterDeduction>(0);

    public House() {
    }

	
    public House(int houseCd, String houseName, double houseRent) {
        this.houseCd = houseCd;
        this.houseName = houseName;
        this.houseRent = houseRent;
    }
    public House(int houseCd, String houseName, double houseRent, Set<MasterDeduction> masterDeductions) {
       this.houseCd = houseCd;
       this.houseName = houseName;
       this.houseRent = houseRent;
       this.masterDeductions = masterDeductions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="house_id", unique=true, nullable=false)
    public Integer getHouseId() {
        return this.houseId;
    }
    
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    
    @Column(name="house_cd", unique=true, nullable=false)
    public int getHouseCd() {
        return this.houseCd;
    }
    
    public void setHouseCd(int houseCd) {
        this.houseCd = houseCd;
    }

    
    @Column(name="house_name", nullable=false, length=45)
    public String getHouseName() {
        return this.houseName;
    }
    
    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    
    @Column(name="house_rent", nullable=false, precision=22, scale=0)
    public double getHouseRent() {
        return this.houseRent;
    }
    
    public void setHouseRent(double houseRent) {
        this.houseRent = houseRent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="house")
    public Set<MasterDeduction> getMasterDeductions() {
        return this.masterDeductions;
    }
    
    public void setMasterDeductions(Set<MasterDeduction> masterDeductions) {
        this.masterDeductions = masterDeductions;
    }




}


