package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * JobStatus generated by hbm2java
 */
@Entity
@Table(name="job_status"
    ,catalog="govt_jute_mill_payroll"
    , uniqueConstraints = @UniqueConstraint(columnNames="job_status_cd") 
)
public class JobStatus  implements java.io.Serializable {


     private Integer jobStatusId;
     private int jobStatusCd;
     private String jobStatusName;
     private Set<MasterData> masterDatas = new HashSet<MasterData>(0);

    public JobStatus() {
    }

	
    public JobStatus(int jobStatusCd, String jobStatusName) {
        this.jobStatusCd = jobStatusCd;
        this.jobStatusName = jobStatusName;
    }
    public JobStatus(int jobStatusCd, String jobStatusName, Set<MasterData> masterDatas) {
       this.jobStatusCd = jobStatusCd;
       this.jobStatusName = jobStatusName;
       this.masterDatas = masterDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="job_status_id", unique=true, nullable=false)
    public Integer getJobStatusId() {
        return this.jobStatusId;
    }
    
    public void setJobStatusId(Integer jobStatusId) {
        this.jobStatusId = jobStatusId;
    }

    
    @Column(name="job_status_cd", unique=true, nullable=false)
    public int getJobStatusCd() {
        return this.jobStatusCd;
    }
    
    public void setJobStatusCd(int jobStatusCd) {
        this.jobStatusCd = jobStatusCd;
    }

    
    @Column(name="job_status_name", nullable=false, length=45)
    public String getJobStatusName() {
        return this.jobStatusName;
    }
    
    public void setJobStatusName(String jobStatusName) {
        this.jobStatusName = jobStatusName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobStatus")
    public Set<MasterData> getMasterDatas() {
        return this.masterDatas;
    }
    
    public void setMasterDatas(Set<MasterData> masterDatas) {
        this.masterDatas = masterDatas;
    }




}


