package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MasterAllowance generated by hbm2java
 */
@Entity
@Table(name="master_allowance"
    ,catalog="govt_jute_mill_payroll"
)
public class MasterAllowance  implements java.io.Serializable {


     private Integer masterAllowanceId;
     private MasterData masterData;
     private double houseRentAllow;
     private double medicalAllow;
     private double mohargoAllow;
     private double childEducation;
     private double convenceAllow;
     private double tiffinAllow;
     private double telephoneAllow;
     private double others;

    public MasterAllowance() {
    }

    public MasterAllowance(MasterData masterData, double houseRentAllow, double medicalAllow, double mohargoAllow, double childEducation, double convenceAllow, double tiffinAllow, double telephoneAllow, double others) {
       this.masterData = masterData;
       this.houseRentAllow = houseRentAllow;
       this.medicalAllow = medicalAllow;
       this.mohargoAllow = mohargoAllow;
       this.childEducation = childEducation;
       this.convenceAllow = convenceAllow;
       this.tiffinAllow = tiffinAllow;
       this.telephoneAllow = telephoneAllow;
       this.others = others;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="master_allowance_id", unique=true, nullable=false)
    public Integer getMasterAllowanceId() {
        return this.masterAllowanceId;
    }
    
    public void setMasterAllowanceId(Integer masterAllowanceId) {
        this.masterAllowanceId = masterAllowanceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public MasterData getMasterData() {
        return this.masterData;
    }
    
    public void setMasterData(MasterData masterData) {
        this.masterData = masterData;
    }

    
    @Column(name="house_rent_allow", nullable=false, precision=22, scale=0)
    public double getHouseRentAllow() {
        return this.houseRentAllow;
    }
    
    public void setHouseRentAllow(double houseRentAllow) {
        this.houseRentAllow = houseRentAllow;
    }

    
    @Column(name="medical_allow", nullable=false, precision=22, scale=0)
    public double getMedicalAllow() {
        return this.medicalAllow;
    }
    
    public void setMedicalAllow(double medicalAllow) {
        this.medicalAllow = medicalAllow;
    }

    
    @Column(name="mohargo_allow", nullable=false, precision=22, scale=0)
    public double getMohargoAllow() {
        return this.mohargoAllow;
    }
    
    public void setMohargoAllow(double mohargoAllow) {
        this.mohargoAllow = mohargoAllow;
    }

    
    @Column(name="child_education", nullable=false, precision=22, scale=0)
    public double getChildEducation() {
        return this.childEducation;
    }
    
    public void setChildEducation(double childEducation) {
        this.childEducation = childEducation;
    }

    
    @Column(name="convence_allow", nullable=false, precision=22, scale=0)
    public double getConvenceAllow() {
        return this.convenceAllow;
    }
    
    public void setConvenceAllow(double convenceAllow) {
        this.convenceAllow = convenceAllow;
    }

    
    @Column(name="tiffin_allow", nullable=false, precision=22, scale=0)
    public double getTiffinAllow() {
        return this.tiffinAllow;
    }
    
    public void setTiffinAllow(double tiffinAllow) {
        this.tiffinAllow = tiffinAllow;
    }

    
    @Column(name="telephone_allow", nullable=false, precision=22, scale=0)
    public double getTelephoneAllow() {
        return this.telephoneAllow;
    }
    
    public void setTelephoneAllow(double telephoneAllow) {
        this.telephoneAllow = telephoneAllow;
    }

    
    @Column(name="others", nullable=false, precision=22, scale=0)
    public double getOthers() {
        return this.others;
    }
    
    public void setOthers(double others) {
        this.others = others;
    }




}


