package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MasterDeduction generated by hbm2java
 */
@Entity
@Table(name="master_deduction"
    ,catalog="govt_jute_mill_payroll"
)
public class MasterDeduction  implements java.io.Serializable {


     private Integer masterDeductionId;
     private House house;
     private MasterData masterData;
     private double telephoneBill;
     private double pfContribution;
     private double pfLoan;
     private double advanceSalary;
     private double revenueStamp;
     private double incomeTax;
     private double electricBill;
     private double others;

    public MasterDeduction() {
    }

    public MasterDeduction(House house, MasterData masterData, double telephoneBill, double pfContribution, double pfLoan, double advanceSalary, double revenueStamp, double incomeTax, double electricBill, double others) {
       this.house = house;
       this.masterData = masterData;
       this.telephoneBill = telephoneBill;
       this.pfContribution = pfContribution;
       this.pfLoan = pfLoan;
       this.advanceSalary = advanceSalary;
       this.revenueStamp = revenueStamp;
       this.incomeTax = incomeTax;
       this.electricBill = electricBill;
       this.others = others;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="master_deduction_id", unique=true, nullable=false)
    public Integer getMasterDeductionId() {
        return this.masterDeductionId;
    }
    
    public void setMasterDeductionId(Integer masterDeductionId) {
        this.masterDeductionId = masterDeductionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="house_id", nullable=false)
    public House getHouse() {
        return this.house;
    }
    
    public void setHouse(House house) {
        this.house = house;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public MasterData getMasterData() {
        return this.masterData;
    }
    
    public void setMasterData(MasterData masterData) {
        this.masterData = masterData;
    }

    
    @Column(name="telephone_bill", nullable=false, precision=22, scale=0)
    public double getTelephoneBill() {
        return this.telephoneBill;
    }
    
    public void setTelephoneBill(double telephoneBill) {
        this.telephoneBill = telephoneBill;
    }

    
    @Column(name="pf_contribution", nullable=false, precision=22, scale=0)
    public double getPfContribution() {
        return this.pfContribution;
    }
    
    public void setPfContribution(double pfContribution) {
        this.pfContribution = pfContribution;
    }

    
    @Column(name="pf_loan", nullable=false, precision=22, scale=0)
    public double getPfLoan() {
        return this.pfLoan;
    }
    
    public void setPfLoan(double pfLoan) {
        this.pfLoan = pfLoan;
    }

    
    @Column(name="advance_salary", nullable=false, precision=22, scale=0)
    public double getAdvanceSalary() {
        return this.advanceSalary;
    }
    
    public void setAdvanceSalary(double advanceSalary) {
        this.advanceSalary = advanceSalary;
    }

    
    @Column(name="revenue_stamp", nullable=false, precision=22, scale=0)
    public double getRevenueStamp() {
        return this.revenueStamp;
    }
    
    public void setRevenueStamp(double revenueStamp) {
        this.revenueStamp = revenueStamp;
    }

    
    @Column(name="income_tax", nullable=false, precision=22, scale=0)
    public double getIncomeTax() {
        return this.incomeTax;
    }
    
    public void setIncomeTax(double incomeTax) {
        this.incomeTax = incomeTax;
    }

    
    @Column(name="electric_bill", nullable=false, precision=22, scale=0)
    public double getElectricBill() {
        return this.electricBill;
    }
    
    public void setElectricBill(double electricBill) {
        this.electricBill = electricBill;
    }

    
    @Column(name="others", nullable=false, precision=22, scale=0)
    public double getOthers() {
        return this.others;
    }
    
    public void setOthers(double others) {
        this.others = others;
    }




}


