package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mill generated by hbm2java
 */
@Entity
@Table(name="mill"
    ,catalog="govt_jute_mill_payroll"
)
public class Mill  implements java.io.Serializable {


     private Integer millId;
     private int millCd;
     private String millName;
     private Set<MasterData> masterDatas = new HashSet<MasterData>(0);

    public Mill() {
    }

	
    public Mill(int millCd, String millName) {
        this.millCd = millCd;
        this.millName = millName;
    }
    public Mill(int millCd, String millName, Set<MasterData> masterDatas) {
       this.millCd = millCd;
       this.millName = millName;
       this.masterDatas = masterDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mill_id", unique=true, nullable=false)
    public Integer getMillId() {
        return this.millId;
    }
    
    public void setMillId(Integer millId) {
        this.millId = millId;
    }

    
    @Column(name="mill_cd", nullable=false)
    public int getMillCd() {
        return this.millCd;
    }
    
    public void setMillCd(int millCd) {
        this.millCd = millCd;
    }

    
    @Column(name="mill_name", nullable=false, length=45)
    public String getMillName() {
        return this.millName;
    }
    
    public void setMillName(String millName) {
        this.millName = millName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mill")
    public Set<MasterData> getMasterDatas() {
        return this.masterDatas;
    }
    
    public void setMasterDatas(Set<MasterData> masterDatas) {
        this.masterDatas = masterDatas;
    }




}


