package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SalaryStatus generated by hbm2java
 */
@Entity
@Table(name="salary_status"
    ,catalog="govt_jute_mill_payroll"
)
public class SalaryStatus  implements java.io.Serializable {


     private Integer salaryStatusId;
     private int salaryStatusCd;
     private String salaryStatusName;
     private Set<MasterData> masterDatas = new HashSet<MasterData>(0);

    public SalaryStatus() {
    }

	
    public SalaryStatus(int salaryStatusCd, String salaryStatusName) {
        this.salaryStatusCd = salaryStatusCd;
        this.salaryStatusName = salaryStatusName;
    }
    public SalaryStatus(int salaryStatusCd, String salaryStatusName, Set<MasterData> masterDatas) {
       this.salaryStatusCd = salaryStatusCd;
       this.salaryStatusName = salaryStatusName;
       this.masterDatas = masterDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="salary_status_id", unique=true, nullable=false)
    public Integer getSalaryStatusId() {
        return this.salaryStatusId;
    }
    
    public void setSalaryStatusId(Integer salaryStatusId) {
        this.salaryStatusId = salaryStatusId;
    }

    
    @Column(name="salary_status_cd", nullable=false)
    public int getSalaryStatusCd() {
        return this.salaryStatusCd;
    }
    
    public void setSalaryStatusCd(int salaryStatusCd) {
        this.salaryStatusCd = salaryStatusCd;
    }

    
    @Column(name="salary_status_name", nullable=false, length=45)
    public String getSalaryStatusName() {
        return this.salaryStatusName;
    }
    
    public void setSalaryStatusName(String salaryStatusName) {
        this.salaryStatusName = salaryStatusName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salaryStatus")
    public Set<MasterData> getMasterDatas() {
        return this.masterDatas;
    }
    
    public void setMasterDatas(Set<MasterData> masterDatas) {
        this.masterDatas = masterDatas;
    }




}


