package com.payroll.govtjutemillpayrollsystem.domain;
// Generated Jul 21, 2018 8:35:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalaryTranDeduction generated by hbm2java
 */
@Entity
@Table(name="salary_tran_deduction"
    ,catalog="govt_jute_mill_payroll"
)
public class SalaryTranDeduction  implements java.io.Serializable {


     private Integer salaryTranDedId;
     private MasterData masterData;
     private SalaryTran salaryTran;
     private double houseRent;
     private double telephoneBill;
     private double waterBill;
     private double electricBill;
     private double gasBill;
     private double pfContribution;
     private double pfLoan;
     private double advanceSalary;
     private double revenueStamp;
     private double incomeTax;
     private double transportDed;
     private double others;

    public SalaryTranDeduction() {
    }

    public SalaryTranDeduction(MasterData masterData, SalaryTran salaryTran, double houseRent, double telephoneBill, double waterBill, double electricBill, double gasBill, double pfContribution, double pfLoan, double advanceSalary, double revenueStamp, double incomeTax, double transportDed, double others) {
       this.masterData = masterData;
       this.salaryTran = salaryTran;
       this.houseRent = houseRent;
       this.telephoneBill = telephoneBill;
       this.waterBill = waterBill;
       this.electricBill = electricBill;
       this.gasBill = gasBill;
       this.pfContribution = pfContribution;
       this.pfLoan = pfLoan;
       this.advanceSalary = advanceSalary;
       this.revenueStamp = revenueStamp;
       this.incomeTax = incomeTax;
       this.transportDed = transportDed;
       this.others = others;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="salary_tran_ded_id", unique=true, nullable=false)
    public Integer getSalaryTranDedId() {
        return this.salaryTranDedId;
    }
    
    public void setSalaryTranDedId(Integer salaryTranDedId) {
        this.salaryTranDedId = salaryTranDedId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public MasterData getMasterData() {
        return this.masterData;
    }
    
    public void setMasterData(MasterData masterData) {
        this.masterData = masterData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="salary_tran_id", nullable=false)
    public SalaryTran getSalaryTran() {
        return this.salaryTran;
    }
    
    public void setSalaryTran(SalaryTran salaryTran) {
        this.salaryTran = salaryTran;
    }

    
    @Column(name="house_rent", nullable=false, precision=22, scale=0)
    public double getHouseRent() {
        return this.houseRent;
    }
    
    public void setHouseRent(double houseRent) {
        this.houseRent = houseRent;
    }

    
    @Column(name="telephone_bill", nullable=false, precision=22, scale=0)
    public double getTelephoneBill() {
        return this.telephoneBill;
    }
    
    public void setTelephoneBill(double telephoneBill) {
        this.telephoneBill = telephoneBill;
    }

    
    @Column(name="water_bill", nullable=false, precision=22, scale=0)
    public double getWaterBill() {
        return this.waterBill;
    }
    
    public void setWaterBill(double waterBill) {
        this.waterBill = waterBill;
    }

    
    @Column(name="electric_bill", nullable=false, precision=22, scale=0)
    public double getElectricBill() {
        return this.electricBill;
    }
    
    public void setElectricBill(double electricBill) {
        this.electricBill = electricBill;
    }

    
    @Column(name="gas_bill", nullable=false, precision=22, scale=0)
    public double getGasBill() {
        return this.gasBill;
    }
    
    public void setGasBill(double gasBill) {
        this.gasBill = gasBill;
    }

    
    @Column(name="pf_contribution", nullable=false, precision=22, scale=0)
    public double getPfContribution() {
        return this.pfContribution;
    }
    
    public void setPfContribution(double pfContribution) {
        this.pfContribution = pfContribution;
    }

    
    @Column(name="pf_loan", nullable=false, precision=22, scale=0)
    public double getPfLoan() {
        return this.pfLoan;
    }
    
    public void setPfLoan(double pfLoan) {
        this.pfLoan = pfLoan;
    }

    
    @Column(name="advance_salary", nullable=false, precision=22, scale=0)
    public double getAdvanceSalary() {
        return this.advanceSalary;
    }
    
    public void setAdvanceSalary(double advanceSalary) {
        this.advanceSalary = advanceSalary;
    }

    
    @Column(name="revenue_stamp", nullable=false, precision=22, scale=0)
    public double getRevenueStamp() {
        return this.revenueStamp;
    }
    
    public void setRevenueStamp(double revenueStamp) {
        this.revenueStamp = revenueStamp;
    }

    
    @Column(name="income_tax", nullable=false, precision=22, scale=0)
    public double getIncomeTax() {
        return this.incomeTax;
    }
    
    public void setIncomeTax(double incomeTax) {
        this.incomeTax = incomeTax;
    }

    
    @Column(name="transport_ded", nullable=false, precision=22, scale=0)
    public double getTransportDed() {
        return this.transportDed;
    }
    
    public void setTransportDed(double transportDed) {
        this.transportDed = transportDed;
    }

    
    @Column(name="others", nullable=false, precision=22, scale=0)
    public double getOthers() {
        return this.others;
    }
    
    public void setOthers(double others) {
        this.others = others;
    }




}


